nodeLinker: node-modules

packageExtensions:
  react-day-picker@*:
    peerDependencies:
      react: ^18.0.0 || ^19.0.0
      react-dom: ^18.0.0 || ^19.0.0

yarnPath: .yarn/releases/yarn-4.9.4.cjs
